version: "3"

services:

    webserver:

        container_name: wabot_api
        build:
            context: .
            dockerfile: Dockerfile
        env_file:
            - .env
        ports:
            - "81:80"
        deploy:
            restart_policy:
                condition: unless-stopped